Importing all the dependencies beforehand

In [1]:
import numpy as np
import pandas as pd

1. Write a Python function to reverse a list.

In [2]:
def func(list_param):
    return list_param[::-1]

original_list = [1, 2, 3, 4, 5]
print("original list: ", original_list, "reversed list: ", func(original_list))

original list:  [1, 2, 3, 4, 5] reversed list:  [5, 4, 3, 2, 1]


2. Create a NumPy array filled with zeros of shape (3, 3).

In [3]:
zero_arr = np.zeros((3, 3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Write a function to check if a given number is prime or not.

In [4]:
def is_prime(num):
    if num < 2:
        return False
    
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    
    return True

num = 45
print("The number is prime." if is_prime(num) else "The number is not prime.")

The number is not prime.


4. How to convert a list of tuples into a pandas DataFrame?

In [5]:
# List of tuples
tuples_list = [('John', 25, 'Male'), ('Jane', 30, 'Female'), ('Bob', 35, 'Male')]

# Create a DataFrame from the list of tuples
df = pd.DataFrame(tuples_list, columns=['Name', 'Age', 'Gender'])

print(df)

   Name  Age  Gender
0  John   25    Male
1  Jane   30  Female
2   Bob   35    Male


5. Implement a function to find the factorial of a number recursively.


In [6]:
def rec_fact(num):
    
    if num <= 1:
        return 1
    
    return rec_fact(num - 1) * num

num = 5
print("The factorial is: ", rec_fact(num))

The factorial is:  120


6. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [7]:
def create_border_array(rows, cols):
    
    # Create an array filled with zeros
    arr = np.zeros((rows, cols), dtype=int)
    
    # Set the border elements to 1
    arr[0, :] = 1  # Top border
    arr[-1, :] = 1  # Bottom border
    arr[:, 0] = 1  # Left border
    arr[:, -1] = 1  # Right border
    
    return arr

rows = 5
cols = 7
border_array = create_border_array(rows, cols)
print(border_array)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


7. Given a list of numbers, write a Python function to find the sum of all the numbers in the list.

In [8]:
def list_sum(list_param):
    
    sum = 0
    
    for i in list_param:
        sum += i
    
    return sum

lt = [1, 2, 3, 4, 5]
print("The sum of the number present in the list: ", list_sum(lt))

The sum of the number present in the list:  15


8. How to count the occurrences of each element in a NumPy array?

In [9]:
arr = np.array([1, 2, 3, 1, 2, 4, 2, 3])
unique_values, counts = np.unique(arr, return_counts=True)

for value, count in zip(unique_values, counts):
    print(value, "occurs", count, "times.\n")

1 occurs 2 times.

2 occurs 3 times.

3 occurs 2 times.

4 occurs 1 times.



9. Write a Python function to check if a string is a palindrome.

In [10]:
def is_palindrome(string):
    
    # Remove whitespace and convert to lowercase
    cleaned_string = ''.join(string.split()).lower()
    
    # Check if the cleaned string is equal to its reverse
    return cleaned_string == cleaned_string[::-1]

print(is_palindrome("racecar"))

True


10. Create a pandas DataFrame from a dictionary where each key-value pair represents a column.

In [11]:
data = {
    'Name': ['John', 'Jane', 'Bob', 'Alice'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   25  New York
1   Jane   30    London
2    Bob   35     Paris
3  Alice   40     Tokyo


11. Implement a function to check if two strings are anagrams of each other.

In [12]:
def are_anagrams(str1, str2):
    
    # Remove whitespace and convert to lowercase
    str1 = ''.join(str1.split()).lower()
    str2 = ''.join(str2.split()).lower()
    
    if len(str1) != len(str2):
        return False
    
    str1_sorted = sorted(str1)
    str2_sorted = sorted(str2)
    
    return str1_sorted == str2_sorted

print(are_anagrams("listen", "silent"))  

True


12. Write a Python function to find the maximum and minimum values in a list.

In [13]:
def find_max_min(list_param):
    
    if not list_param:
        return None, None
    
    max_val = min_val = list_param[0]
    
    for num in list_param:
        if num > max_val:
            max_val = num
        elif num < min_val:
            min_val = num
    
    return max_val, min_val

numbers = [5, 2, 8, 1, 9, 3]
maximum, minimum = find_max_min(numbers)
print("Maximum value: ", maximum, "Minimum value: ", minimum)

Maximum value:  9 Minimum value:  1


13. Create a NumPy array with values ranging from 1 to 10.

In [14]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


14. How to transpose a NumPy array?

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


15. Write a Python function to remove duplicates from a list.


In [16]:
def remove_duplicates(list_param):
    
    unique_set = set(list_param)
    
    unique_list = list(unique_set)
    
    return unique_list

original_list = [1, 2, 3, 2, 4, 1, 5, 6, 6]
unique_list = remove_duplicates(original_list)
print(unique_list)  

[1, 2, 3, 4, 5, 6]


16. Implement a function to find the intersection of two lists.


In [17]:
def find_intersection(list1, list2):
    
    set1 = set(list1)
    set2 = set(list2)
    
    intersection_set = set1 & set2
    
    intersection_list = list(intersection_set)
    
    return intersection_list

list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
intersection = find_intersection(list1, list2)
print(intersection)  

[4, 5]


17. Write a NumPy program to compute the determinant of a given square array.



In [18]:
def compute_determinant(arr):
    
    if arr.shape[0] != arr.shape[1]:
        print("Input array must be square.")
        return False
    
    determinant = np.linalg.det(arr)
    
    return determinant

square_array = np.array([[8, 5],
                         [4, 5]])
det = compute_determinant(square_array)
print(f"The determinant of the array is: {det}")

The determinant of the array is: 19.999999999999996


18. How to sort a pandas DataFrame by a specific column?


In [19]:
data = {'Name': ['John', 'Jane', 'Bob', 'Alice'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
df_sorted = df.sort_values(by='Age')
print(df_sorted)

    Name  Age      City
0   John   25  New York
1   Jane   30    London
2    Bob   35     Paris
3  Alice   40     Tokyo


19. Create a Python function to generate the Fibonacci sequence up to n terms.


In [20]:
def fibonacci_sequence(n):
    
    sequence = [0, 1]
    
    for i in range(2, n):
        next_term = sequence[i-1] + sequence[i-2]
        sequence.append(next_term)
    
    return sequence

num_terms = 10
fib_sequence = fibonacci_sequence(num_terms)
print(fib_sequence)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


20. Write a NumPy program to compute the inner product of two given vectors.


In [21]:
def compute_inner_product(vec1, vec2):
    
    if vec1.shape != vec2.shape:
        print("Input vectors must have the same shape.")
        return False
    
    inner_product = np.dot(vec1, vec2)
    
    return inner_product

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result = compute_inner_product(vector1, vector2)
print("The inner product of the vectors is: ", result)

The inner product of the vectors is:  32


21. Implement a function to flatten a nested list.


In [22]:
def flatten_list(nested_list):
    
    flat_list = []
    
    def flatten(lst):
        for item in lst:
            if isinstance(item, list):
                flatten(item)
            else:
                flat_list.append(item)
    
    flatten(nested_list)
    return flat_list

nested_list = [1, 2, [3, 4], [5, [6, 7]], 8]
flattened_list = flatten_list(nested_list)
print(flattened_list)  

[1, 2, 3, 4, 5, 6, 7, 8]


22. Write a Python function to check if a number is even or odd.

In [23]:
def is_even(num):
    
    return num % 2 == 0

print("Even" if is_even(5) else "Odd") 

Odd


23. How to rename columns in a pandas DataFrame?


In [24]:
data = {'Name': ['John', 'Jane', 'Bob', 'Alice'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
print(df, '\n')
df = df.rename(columns={'Name': 'FirstName', 'Age': 'Years'})
print(df)

    Name  Age      City
0   John   25  New York
1   Jane   30    London
2    Bob   35     Paris
3  Alice   40     Tokyo 

  FirstName  Years      City
0      John     25  New York
1      Jane     30    London
2       Bob     35     Paris
3     Alice     40     Tokyo


24. Create a NumPy array of random integers between 1 and 100.

In [25]:
random_array = np.random.randint(1, 101, size=10)
print(random_array)

[ 57  80  14  32 100  87  41  41  19  50]


25. Write a Python function to find the median of a list.


In [26]:
def find_median(lst):
    
    sorted_lst = sorted(lst)
    n = len(sorted_lst)
    
    if n % 2 == 0:
        middle1 = sorted_lst[n // 2 - 1]
        middle2 = sorted_lst[n // 2]
        median = (middle1 + middle2) / 2
    else:
        median = sorted_lst[n // 2]
    
    return median

numbers = [5, 2, 8, 1, 9, 3, 7]
median_value = find_median(numbers)
print("The median of the list is: ", median_value)

The median of the list is:  5


26. Implement a function to rotate a list to the right by k steps.


In [27]:
def rotate_list(list_param, k):
    
    k = k % len(list_param)
    
    # Slice the list into two parts
    left_part = list_param[:-k]
    right_part = list_param[-k:]
    
    # Rotate the list by concatenating the two parts
    rotated_list = right_part + left_part
    
    return rotated_list

original_list = [1, 2, 3, 4, 5]
rotated_list = rotate_list(original_list, 2)
print(rotated_list)  

[4, 5, 1, 2, 3]


27. Write a NumPy program to compute the mean, median, and mode of a given array.


In [28]:
from scipy import stats

def compute_stats(arr):
    
    # Compute the mean
    mean_val = np.mean(arr)
    
    # Compute the median
    median_val = np.median(arr)
    
    # Compute the mode
    mode_val = stats.mode(arr)[0][0]
    
    return mean_val, median_val, mode_val

# Example usage
data = np.array([1, 2, 3, 4, 2, 3, 4, 1, 2, 3])
mean, median, mode = compute_stats(data)
print("Mean:", mean, "Median:", median,  "Mode:", mode)

Mean: 2.5 Median: 2.5 Mode: 2


/var/folders/n2/shlj0pzn3fn2928f1734jn580000gn/T/ipykernel_11527/3161243915.py:12: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_val = stats.mode(arr)[0][0]


28. How to concatenate two pandas DataFrames?
29. Create a Python function to generate all possible permutations of a list.
30. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
31. Implement a function to check if a string contains only digits.
32. Write a Python function to check if a given year is a leap year.
33. How to drop missing values from a pandas DataFrame?
34. Create a NumPy array with random floats between 0 and 1.
35. Write a Python function to calculate the power of a number using recursion.
36. Implement a function to calculate the factorial of a number using dynamic programming.
37. Write a NumPy program to compute the outer product of two given vectors.
38. How to convert a pandas DataFrame to a NumPy array?
39. Create a Python function to check if a given string is a valid email address.
40. Write a NumPy program to compute the cross product of two given vectors.
41. Implement a function to check if a list is sorted in ascending order.
42. Write a Python function to find the longest common prefix of a list of strings.
43. How to drop duplicate rows from a pandas DataFrame?
44. Create a NumPy array with evenly spaced values between 1 and 10.
45. Write a Python function to find the GCD (Greatest Common Divisor) of two numbers.
46. Implement a function to check if a string contains only vowels.
47. Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.
48. How to group rows in a pandas DataFrame by a specific column?
49. Create a Python function to check if a given string is a valid IPv4 address.
50. Write a NumPy program to compute the percentile of a given NumPy array.